### ISSUE TITLE
stacker site doesn't work

### ISSUE THREAD

**Issue by paco-portada** [santoshbaggam/stacker#4]
I have installed stacker:
curl -sSL https://raw.githubusercontent.com/santoshbaggam/stacker/master/install.sh | bash
stacker build
It worked ok.

When I exec stacker alumno.mobi, I receive this error:
Err: Invalid command. Check the docs at https://github.com/santoshbaggam/stacker

I don't know what is wrong.
Can you help me?

Thanks

**Comment by santoshbaggam** [comment]
You need to run `stacker site` and then follow the prompts to create a site. The **site** keyword itself is a command.
Let me know if that doesn't work.
